### ISSUE TITLE
child theme / css

### ISSUE THREAD

**Issue by paulnett** [obenland/the-bootstrap#11]
re: child theme / css

i did some changes to 'the-bootstrap' functions.php file so that the calls to the css files use 'get stylesheet', instead of 'get template'.
this allows for me to reference the child theme's versions of 'bootstrap' and 'bootstrap-min' css files. 

this seems to be the only way i can make changes that render. i would rather not edit the parent themes functions.php file, and i would rather just make changes in the child themes css file. 

can you explain what would be the best way to use the child theme files rather than edit the parent theme?

**Comment by obenland** [comment]
The best way would probably to hook into <code>'init'</code> on a priority of >10 in you <code>functions.php</code> file.
Then you can deregister the stylesheets from the Parent Theme and register you own. If you use the same handles, they  also should be enqueued automatically.

**Comment by paulnett** [comment]
Stoked! Got it working. Thanks a ton. I have another question in regards to page templates. I will open a new issue.
