### ISSUE TITLE
Page Templates

### ISSUE THREAD

**Issue by paulnett** [obenland/the-bootstrap#12]
I have a question about page templates.
I don't have the option to select a different page template for each of my pages.
I do see there is a templates folder with a full width version inside.
How do I access for pages? Is the option to select different templates only enabled for posts?

Other sites I admin have the option to change page templates for a page.

**Comment by paulnett** [comment]
To see the option for the full width template, I moved the file outside the 'templates' folder. Would this be the correct method?

**Comment by obenland** [comment]
If you do it in your Child Theme yes. :)

I have it in the folder as a goodie for WordPress 3.4 users. In 3.4 page templates in folders get found.
