### ISSUE TITLE
Can't 'uncheck' Add searchform to navigation bar?

### ISSUE THREAD

**Issue by flickster** [obenland/the-bootstrap#14]
Thanks for an awesome theme! I have only just started working with it but am so glad that someone has merged Bootstrap with WordPress to make it easier for the rest of us to find our feet.

I have a small question re: the option called 'Add searchform to navigation bar' in Theme Options, because for some reason, when I try and uncheck this option and press Save Changes to confirm the change, when the page reloads the option remains checked. Not sure if its because I'm using a child theme?

Thanks!

**Comment by obenland** [comment]
Hi flickster,

thank you for your feedback, I'm glad you like it!

I had that bug fixed originally, but it keeps creeping back up. With c5548114029130dfb3eae61ce43ac8d4d4766f1d I hope it'll be gone for good. The new version 1.6.0 has already been approved, I'm currently just waiting for it to get synced to extend.

Thank you for using The Bootstrap!

Konstantin

**Comment by flickster** [comment]
Hi Konstantin

Many thanks for your reply. I have just updated to 1.6.0 and can confirm that this fixes the problem. :)

Kind Regards
Flick
