### ISSUE TITLE
Less wide in IE(8) than in Chrome or Firefox?

### ISSUE THREAD

**Issue by flickster** [obenland/the-bootstrap#15]
Hi again 

Sorry to raise another question so soon after my last one (thank you for your help, Konstantin with that one) I have been viewing the test site I am working on Chrome, Firefox and IE(8) and have been really happy with how the site is working in the first two browsers (inevitably :p) and having to tweak small things just for IE.  

However, one thing I have noticed is that - out of the box - the full width of The Bootstrap seems to be more narrow in IE than in Chrome or Firefox.

Put another way - the spaces to the left and right of the main content appear wider in IE, so the sidebar and content become more 'squished'.

Apologies for this really strange question, but any advice would be much appreciated about how best to change the display on IE.

Many thanks

Kind Regards
Flick

**Comment by flickster** [comment]
/me is proud to have her first props, ever ;)  Thanks again!

**Comment by obenland** [comment]
:) Sure thing! Thanks again for contributing!

**Comment by flickster** [comment]
Hi Konstantin :D  Sorry to comment on this issue again.  I thought that the initial change had fixed the issue for me, but it turns out that I needed to enqueue it so that respond.min.js loaded after all the stylesheets (ref: http://stackoverflow.com/a/9137539/1470820) - for my child theme at least - and then the site loaded beautifully in IE8.  

I presume this would involve moving the respond.js bit to the parent theme functions.php with the other bootstrap js/css files, but am not sure. Would it be possible or convenient for you to advise me on this please?

Thanks :D

**Comment by flickster** [comment]
May apologies - having just made this post, I realised upon browsing 1.7.0 that you had already addressed this issue in 08c28eaec7ec2f376fcb67e79925b281cb1cf2f7  Thanks again :D
