### ISSUE TITLE
category.php 'not-found' partials?

### ISSUE THREAD

**Issue by flickster** [obenland/the-bootstrap#18]
Hi again :)

Sorry to bother you with a small issue this time but I was wondering if Line 36 from category.php

`get_template_part( '/partials/content', 'not-found' );`

should be 

``get_template_part( '/partials/content', 'no-results' );`

instead?

Thanks

**Comment by obenland** [comment]
Good eye! I didn't notice, thanks!

**Comment by flickster** [comment]
Thanks again Konstantin :)   Is it possible to advise on when 1.7.x will be pushed to the WP repository please?

**Comment by obenland** [comment]
Hm, it's hard to say. I have it there already for review. Maybe a week?
If you want to update earlier, grab the 1.7.1 zip download and update it manually.

**Comment by flickster** [comment]
Thanks :) I think I'll do as you suggested with the 1.7.1 download as I'm about to finalise a site so will need to ensure the child theme templates are up-to-date.
