### ISSUE TITLE
Header image - responsiveness

### ISSUE THREAD

**Issue by flickster** [obenland/the-bootstrap#19]
With reference to the question posed [here](http://wordpress.org/support/topic/theme-the-bootstrap-header-image-responsive-proportions-issue) - it suddenly reminded me that I added an extra class to my child theme header-image code (in header.php)  
`<img src="<?php header_image(); ?>" width="<?php echo get_custom_header()->width; ?>" height="<?php echo get_custom_header()->height; ?>" alt="" class="wp-image-" />`

as it then allowed the image to expand and contract as usual. In hindsight, this is probably better adjusted using the stylesheet instead?

Thanks :)

**Comment by obenland** [comment]
Yes, I added the selector in b2197257e0, this is also fixed in 1.7.1 :)

**Comment by flickster** [comment]
My bad for not spotting the fix! Sorry for the extra hassle. >_<

**Comment by obenland** [comment]
Now worries. I rather have it this way than potentially having a buggy Theme :)
