### ISSUE TITLE
Thumbnail image not visible in iPhone

### ISSUE THREAD

**Issue by baoshi** [obenland/the-bootstrap#23]
Hello,
I have encountered a thumbnail image display problem when browse in iPhone.

To reproduce it, try browse to http://the-bootstrap.obenland.it/post-format-test-gallery/ from iPhone, you will find all the gallery images are reduced to 1x1px square. Same results are encountered for thumbnail image on my page http://www.ba0sh1.com

I can reproduce this using Safari under OS X, by reducing the windows width. However if I drag the window wider, the thumbnail images will be shown and if I again reduce the windows width, the thumbnail images are persistent.

This problem does not happen on other browsers such as Chrome on iPhone. It does not happen on Safari for iPad either.

**Comment by obenland** [comment]
Hi baoshi,

thank you for your opening this issue!
I tracked it back to an IE8 hack, to properly display thumbnail images. I'll have it fixed soon.

Thanks again!

**Comment by obenland** [comment]
I should have fixed it now on http://the-bootstrap.obenland.it/post-format-test-gallery/

Would you mind double-checking?

Thanks!

**Comment by baoshi** [comment]
Yes!
I have tried Safari on iPhone and OSX, both working.
Thanks!

Baoshi

**Comment by baoshi** [comment]
Yes!
I have tried Safari on iPhone and OSX, both working.
Thanks!

Baoshi

On Jul 23, 2012, at 10:41 PM, Konstantin Obenland wrote:

I should have fixed it now on
http://the-bootstrap.obenland.it/post-format-test-gallery/

Would you mind double-checking?

Thanks!

---
