### ISSUE TITLE
Opera 12 oTransitionEnd Bugs and Workarounds

### ISSUE THREAD

**Issue by amwestg** [obenland/the-bootstrap#24]
Opera 12 and Carousel 2.0.4 not work correctly.

Issue and Patch ==>  https://github.com/twitter/bootstrap/issues/4128

**Comment by obenland** [comment]
Hi amwestg,

thank you for letting me know!
Since this is a Bootstrap issue wich will be fixed in 2.1 I rather wait for the update.
I just did a bug-fix release today, so it would be waiting pretty long to go live anyway.

Thanks,
Konstantin

**Comment by amwestg** [comment]
Hi Konstantin;

I would prefer that you make this patch. The patch is quite simple, a one 
line change to the theme's bootstrap.js and bootstrap.min.js.

These changes are currently in my child theme since it is a Bootstrap issue 
and I need a method of maintaining bug fixes for Bootstrap independently 
from whatever bug-fixes you plan on releasing in the future.  I really don't 
like the idea of adding these files to a child theme as it does open up 
maintenance issues and the possibility of the child theme not working in the 
future.

Regards,
Gerry Allen

-----Original Message-----
