### ISSUE TITLE
Use media-list for comments markup

### ISSUE THREAD

**Issue by hpatoio** [obenland/the-bootstrap#38]
Hello, on Bootstrap 2.2.0 there is a "media" components http://twitter.github.com/bootstrap/components.html#media that, as the doc says, used inside a list is good/meant to style comments.

Would be nice to have that mark up for the comments list.

Thanks
## 

Simone

**Comment by obenland** [comment]
Thank you for reaching out! I'll definitely check into integrating that! :)
