### ISSUE TITLE
Font Awesome iconic fonts instead of Glyphicons

### ISSUE THREAD

**Issue by raphaelsuzuki** [obenland/the-bootstrap#40]
Hi!

Have you considered packing Font Awesome iconic fonts instead of Glyphicons PNG?

Fonts scale much better, absorb the element's style and can be styled, and are much more complete (over 200 icons).

Also, integration is plain and simple.

**Comment by raphaelsuzuki** [comment]
I forgot the link to the project: http://fortawesome.github.com/Font-Awesome/

**Comment by obenland** [comment]
Hi Raphael,

thank you for reaching out! :)

The Bootstrap is meant to be a very basic theme to help getting started with WordPress and Bootstrap. With that, the goal would be to alter Bootstrap as few as possible and stick to what it ships with.

Thanks,
Konstantin

**Comment by raphaelsuzuki** [comment]
Ok.

Some add-ons made for Bootstrap would help even further.

Thanks.
