### ISSUE TITLE
Pagination Issue

### ISSUE THREAD

**Issue by paulnett** [obenland/the-bootstrap#42]
Like this theme.. Learning as I go.
Question about pagination. Can't seem to get it to work on a custom page (page-blog.php).
Any suggestions?

![Screen Shot 2012-12-17 at 12 00 02 AM](https://f.cloud.github.com/assets/1237680/16255/ca8bf69e-481f-11e2-9fac-2554d9896539.png)

**Comment by obenland** [comment]
I'm sorry this is a development issue tracker, not a support forum.
Please post development questions that are not theme bugs over at the WordPress Support Forum:
http://wordpress.org/support/theme/the-bootstrap

Thanks!
