### ISSUE TITLE
Paginated posts will break layout

### ISSUE THREAD

**Issue by ktm11** [obenland/the-bootstrap#43]
Just use  in any post to split the post in 2 or more pages then if you go the page 2 of the paginated post the sidebar will go below comments section, breaking the layout.

**Comment by obenland** [comment]
Thank you for letting me know, @ktm11!

Can you provide me with a link to a site where this issue occurs?
I could not reproduce it on [my demo site](http://the-bootstrap.obenland.it/layout-test/2/).
