### ISSUE TITLE
Gallery widget and carousel not working

### ISSUE THREAD

**Issue by raeannewright** [obenland/the-bootstrap#51]
Hi there,

I'm just getting started with this theme and I love it! Just one issue I've run into: the gallery widget and auto-carousel do not seem to work. 

I've created a post, added a gallery with the Add Media button, assigned it the post type 'gallery' and published the post. Then, I added the widget and selected the post, but nothing appears in the sidebar. Other widgets in the same sidebar show up, but the gallery widget does not - in the source, there is nothing at all where the widget should be. Furthermore, the post itself does not show the slick slider, but the standard gallery layout. 

Is there something I'm missing?

Thank you for your help and for a great theme!
Raeanne

**Comment by obenland** [comment]
I'm sorry this is a development issue tracker, not a support forum.
Please post development questions that are not theme bugs over at the WordPress Support Forum:
http://wordpress.org/support/theme/the-bootstrap

Thanks!
